- name: Configure Minecraft Server
  hosts: minecraft
  become: yes
  tasks:
    - name: Install Java 21 via Corretto tarball
      shell: |
        cd /home/ec2-user
        rm -rf java21 corretto-21.tar.gz
        wget https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz -O corretto-21.tar.gz
        mkdir java21
        tar -xzf corretto-21.tar.gz -C java21 --strip-components=1
      args:
        executable: /bin/bash
      become: false

    - name: Create Minecraft directory
      file:
        path: /home/ec2-user/minecraft
        state: directory
        owner: ec2-user

    - name: Download server.jar
      get_url:
        url: https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /home/ec2-user/minecraft/server.jar
        owner: ec2-user

    - name: Accept EULA
      copy:
        dest: /home/ec2-user/minecraft/eula.txt
        content: "eula=true\n"
        owner: ec2-user

    - name: Create Minecraft systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          WorkingDirectory=/home/ec2-user/minecraft
          ExecStart=/home/ec2-user/java21/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          User=ec2-user
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started
